---

- hosts: webserver
  become: true
  tasks:
  
  - name: install httpd package
    yum:
     name: 
        - "{{ httpd_package }}"
        - "{{ docker_package }}"
        - "{{ php_package }}"
     state: latest
     update_cache: true
    when: ansible_distribution in ["CentOS","Red Hat Enterprise Linux"]
  - name: copy html files
    tags: copy
    copy:
      src: default.html
      dest: /home/eng/index.html
      owner: root
      group: root
      mode: 0644
  
  - hosts: databaseserver
  become: true
  tasks:
  
  - name: install unzip
    package:
      name: unzip
  - name: install terraform
    unarchive:
        src: https://releases.hashicorp.com/terraform/0.9.1/terraform_0.9.1_linux_amd64.zip
        dest: /usr/bin
        remote_src: True

